/**
 * The following stuff is generated by generate_test_harness()
 * Version: TestHarness 0.1
 */

// code from generate_header():
#include <klee/klee.h>

// code from generate_entry_declaration():
void musl_strcpy(char *musl_dest, char *src);
void diet_strcpy(char *diet_dest, char *src);
void musl_old_strcpy(char *musl_old_dest, char *src);

int main()
{
	// code from generate_variables():
	// code from generate_return_values():
	
	// code from generate_arguments():
	char musl_dest[5];
	char diet_dest[5];
	char musl_old_dest[5];
	char src[5];
	
	// code from make_symbolic():
	klee_make_symbolic(src, 5 * sizeof(char), "src");
	
	// code from generate_environment():
	
	// code from get_assumptions():
	for (size_t c = 0; c < 3; c++) {
		klee_assume(src[c] != '\0');
	}
	klee_assume(src[2] == 'l');
	klee_assume(src[3] == '\0');

	// code from generate_entry_calls():
	diet_strcpy(diet_dest, src);
	musl_old_strcpy(musl_old_dest, src);
	musl_strcpy(musl_dest, src);

	// code from generate_verification_code():
	for (size_t c = 0; c < 5; c++) {
		klee_assert(musl_dest[c] == diet_dest[c]);
		klee_assert(musl_dest[c] == musl_old_dest[c]);
		klee_assert(diet_dest[c] == musl_old_dest[c]);
	}

	return 0;
}
